AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

Parameters:
  WebDomain:
    Type: String
  BucketImageName:
    Type: String
  BucketStaticSiteName:
    Type: String

Resources:
  DynamoDbReceptacleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./dynamodb/dynamoDbReceptacle.yaml

  CreatePointLambdaStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambda/lambdaReceptacle.yaml
      Parameters:
        DynamoDbArn: !GetAtt DynamoDbReceptacleStack.Outputs.DynamoDbArn

  GetPointsLambdaStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambda/getPoints.yaml
      Parameters:
        DynamoDbArn: !GetAtt DynamoDbReceptacleStack.Outputs.DynamoDbArn

  AppSyncReceptacleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./appsync/appSyncReceptacle.yaml
      Parameters:
        CreatePointLambdaArn: !GetAtt CreatePointLambdaStack.Outputs.CreatePointLambdaArn
        GetPointsLambdaArn: !GetAtt GetPointsLambdaStack.Outputs.GetPointsLambdaArn

  S3BucketImagesStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./s3/bucket-images.yaml
      Parameters:
        BucketName: !Ref BucketImageName
        WebDomain: !Ref WebDomain

  S3BucketStaticSiteStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./s3/static-site.yaml
      Parameters:
        BucketName: !Ref BucketStaticSiteName

  IdentityPoolStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cognito/identityPool.yaml
      Parameters:
        BucketName: !Ref BucketImageName
        AppSyncApiArn: !GetAtt AppSyncReceptacleStack.Outputs.AppSyncApiArn

Outputs:
  IdentityPoolId:
    Value: !GetAtt IdentityPoolStack.Outputs.IdentityPoolId
  UserPoolId:
    Value: !GetAtt IdentityPoolStack.Outputs.UserPoolId
  UserPoolClientId:
    Value: !GetAtt IdentityPoolStack.Outputs.UserPoolClientId
  AppSyncApiEndpoint:
    Value: !GetAtt AppSyncReceptacleStack.Outputs.AppSyncApiEndpoint
