version = 0.1
[default.deploy.parameters]
stack_name = "s3Bucket"
resolve_s3 = true
s3_prefix = "s3Bucket"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=\"stg-receptacle-images\" WebDomain=\"https://stg.jayraldempino.pro\""
image_repositories = []
