AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  DynamoDB for Say Green

Resources:
  ReceptacleDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: say-green
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      AttributeDefinitions:
        - AttributeName: hash
          AttributeType: N
        - AttributeName: range
          AttributeType: S
        - AttributeName: geohash
          AttributeType: N
      KeySchema:
        - AttributeName: hash
          KeyType: HASH
        - AttributeName: range
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      LocalSecondaryIndexes:
        - IndexName: hash-geohash
          KeySchema:
            - AttributeName: hash
              KeyType: HASH
            - AttributeName: geohash
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  DynamoDbArn:
    Value: !GetAtt ReceptacleDB.Arn
    Export: 
      Name: DynamoDbArn
