AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  DynamoDB for Say Green

Resources:
  ReceptacleDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SayGreen
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      AttributeDefinitions:
        - AttributeName: hash
          AttributeType: S
        - AttributeName: sort
          AttributeType: S
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: hash
          KeyType: HASH
        - AttributeName: sort
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: typeHash
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: hash
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: typeSort
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: sort
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  DynamoDbArn:
    Value: !GetAtt ReceptacleDB.Arn
    Export: 
      Name: DynamoDbArn
