AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ""

Parameters:
  CreatePointLambdaArn:
    Type: String

Resources:
  AppSyncApiReceptacle:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: Receptacle
      ApiType: GRAPHQL
      AuthenticationType: AWS_IAM
      Visibility: GLOBAL

  AppSyncSchemaReceptacle:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncApiReceptacle.ApiId
      DefinitionS3Location: ../graphql/receptacleSchema.graphql

  AppSyncCreatePointDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApiReceptacle.ApiId
      Name: StoreReceptacle
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn: !Ref CreatePointLambdaArn
      ServiceRoleArn: !GetAtt LambdaDataSourceServiceCreatePointRole.Arn

  AppSyncCreatePointResolver:
    Type: AWS::AppSync::Resolver
    DependsOn:
      - AppSyncSchemaReceptacle
    Properties:
      ApiId: !GetAtt AppSyncApiReceptacle.ApiId
      Kind: UNIT
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "operation": "Invoke",
          "payload": $util.toJson($context.args)
        }
      ResponseMappingTemplate: $util.toJson($context.result)
      FieldName: createPoint
      TypeName: Mutation
      DataSourceName: !GetAtt AppSyncCreatePointDataSource.Name

  LambdaDataSourceServiceCreatePointRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appsync.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaFunctionGetSessionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Ref CreatePointLambdaArn

Outputs:
  AppSyncApiArn:
    Value: !GetAtt AppSyncApiReceptacle.Arn
    Export:
      Name: AppSyncApiArn
  AppSyncApiEndpoint:
    Value: !GetAtt AppSyncApiReceptacle.GraphQLUrl
    Export:
      Name: AppSyncApiEndpoint
