AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

Parameters:
  DynamoDbArn:
    Type: String
    Default: !ImportValue DynamoDbArn

Resources:
  StoreReceptacleFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: StoreReceptacleFunction
      CodeUri: ../../functions/storeReceptacleLambda
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "dynamodb:PutItem"
                - "dynamodb:DeleteItem"
                - "dynamodb:Query"
              Resource:
                - !Sub "${DynamoDbArn}/*"
                - !ImportValue DynamoDbArn

Outputs:
  StoreReceptacleFunctionArn:
    Value: !GetAtt StoreReceptacleFunction.Arn
    Export:
      Name: StoreReceptacleFunctionArn
