name: Say Green Deployment

on:
  push:
    branches: [ master ]

jobs:
  static-site-generation:
    name: Deployment to S3 as static website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v2
        with: 
          node-version: 20.10
      - name: Install dependencies and build
        run: |
          npm install
          npm run build