name: Say Green Deployment

on:
  push:
    branches: [ master ]

jobs:
  static-site-generation:
    name: Deployment to S3 as static website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v2
        with: 
          node-version: 20.10.0
      - name: Install dependencies
        run: |
          npm install
      - name: Add amplifyconfiguration.json
        run: |
          echo '{
            "aws_cognito_region": "${{ secrets.GENERAL_REGION }}"
            "aws_cognito_identity_pool_id": "${{ secrets.COGNITO_IDENTITY_POOL_ID }}",
            "aws_project_region": "${{ secrets.GENERAL_REGION }}",
            "aws_appsync_graphqlEndpoint": "${{ vars.APPSYNC_API_ENDPOINT }}",
            "aws_appsync_region": "${{ secrets.GENERAL_REGION }}",
            "aws_appsync_authenticationType": "${{ vars.APPSYNC_AUTH_TYPE }}"
          }' > src/amplifyconfiguration.json
      - name: Build source
        env:
          MAPBOX_GL_ACCESS_TOKEN: ${{ secrets.MAPBOX_GL_ACCESS_TOKEN }}
          BOUNDARY_COORDINATE_LNG_TOP_LEFT: ${{ vars.BOUNDARY_COORDINATE_LNG_TOP_LEFT }}
          BOUNDARY_COORDINATE_LAT_TOP_LEFT: ${{ vars.BOUNDARY_COORDINATE_LAT_TOP_LEFT }}
          BOUNDARY_COORDINATE_LNG_TOP_RIGHT: ${{ vars.BOUNDARY_COORDINATE_LNG_TOP_RIGHT }}
          BOUNDARY_COORDINATE_LAT_TOP_RIGHT: ${{ vars.BOUNDARY_COORDINATE_LAT_TOP_RIGHT }}
          BOUNDARY_COORDINATE_LNG_BOTTOM_RIGHT: ${{ vars.BOUNDARY_COORDINATE_LNG_BOTTOM_RIGHT }}
          BOUNDARY_COORDINATE_LAT_BOTTOM_RIGHT: ${{ vars.BOUNDARY_COORDINATE_LAT_BOTTOM_RIGHT }}
          BOUNDARY_COORDINATE_LNG_BOTTOM_LEFT: ${{ vars.BOUNDARY_COORDINATE_LNG_BOTTOM_LEFT }}
          BOUNDARY_COORDINATE_LAT_BOTTOM_LEFT: ${{ vars.BOUNDARY_COORDINATE_LAT_BOTTOM_LEFT }}
        run: |
          npm run build