name: Resources spin up

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    outputs:
      appSyncApiEndpoint:
        value: ${{ jobs.resource-spin-up.outputs.appSyncApiEndpoint }}
      identityPoolId:
        value: ${{ jobs.resource-spin-up.outputs.identityPoolId }}
      userPoolId:
        value: ${{ jobs.resource-spin-up.outputs.userPoolId }}
      userPoolClientId:
        value: ${{ jobs.resource-spin-up.outputs.userPoolClientId }}

jobs:
  resource-spin-up:
    name: Resources spin up for ${{ inputs.environment }} environment
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      appSyncApiEndpoint: ${{ steps.sam-outputs.outputs.appSyncApiEndpoint }}
      identityPoolId: ${{ steps.sam-outputs.outputs.identityPoolId }}
      userPoolId: ${{ steps.sam-outputs.outputs.userPoolId }}
      userPoolClientId: ${{ steps.sam-outputs.outputs.userPoolClientId }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.GENERAL_REGION }}
      - run: |
          sam build --template-file sam/template.yaml --use-container --build-image public.ecr.aws/sam/build-go1.x && \
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
                BucketImageName=${{ vars.BUCKET_IMAGE_NAME }} \
                BucketStaticSiteName=${{ vars.BUCKET_SITE_NAME }} \
                WebDomain=https://${{ vars.BUCKET_SITE_NAME }} \
            --stack-name say-green \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
            --on-failure ROLLBACK
      - run: |
          outputs=$(aws cloudformation describe-stacks --stack-name say-green --query 'Stacks[0].Outputs' --output json)
          echo $outputs > outputs.json
      - id: sam-outputs
        run: |
          appSyncApiEndpoint=$(jq -r '.[] | select(.OutputKey == "AppSyncApiEndpoint").OutputValue' outputs.json)
          identityPoolId=$(jq -r '.[] | select(.OutputKey == "IdentityPoolId").OutputValue' outputs.json)
          userPoolId=$(jq -r '.[] | select(.OutputKey == "UserPoolId").OutputValue' outputs.json)
          userPoolClientId=$(jq -r '.[] | select(.OutputKey == "UserPoolClientId").OutputValue' outputs.json)
          echo "appSyncApiEndpoint=$appSyncApiEndpoint" >> "$GITHUB_OUTPUT"
          echo "identityPoolId=$identityPoolId" >> "$GITHUB_OUTPUT"
          echo "userPoolId=$userPoolId" >> "$GITHUB_OUTPUT"
          echo "userPoolClientId=$userPoolClientId" >> "$GITHUB_OUTPUT"
