projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - app/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - app/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: app/API.ts
        docsFilePath: app/graphql
        region: ap-southeast-1
        apiId: 3rjilvhwqjfmhax3hlkysw35we
        frontend: javascript
        framework: react
        maxDepth: 3
